// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package com.johnsnowlabs.grpc;

public interface nlp_inputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.nlp_input)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
