// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package com.johnsnowlabs.grpc;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_nlp_input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_nlp_input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_nlp_output_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_nlp_output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020definition.proto\022\nrouteguide\"\031\n\tnlp_in" +
      "put\022\014\n\004text\030\001 \001(\t\"\034\n\nnlp_output\022\016\n\006resul" +
      "t\030\001 \001(\t2\261\001\n\010SparkNLP\0226\n\003clf\022\025.routeguide" +
      ".nlp_input\032\026.routeguide.nlp_output\"\000\0226\n\003" +
      "ner\022\025.routeguide.nlp_input\032\026.routeguide." +
      "nlp_output\"\000\0225\n\002re\022\025.routeguide.nlp_inpu" +
      "t\032\026.routeguide.nlp_output\"\000B6\n\033io.grpc.e" +
      "xamples.routeguideB\017RouteGuideProtoP\001\242\002\003" +
      "RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_routeguide_nlp_input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_routeguide_nlp_input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_nlp_input_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_routeguide_nlp_output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_routeguide_nlp_output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_nlp_output_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
