// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package com.johnsnowlabs.grpc_async;

public interface nlp_outputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_async.nlp_output)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
