// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package com.johnsnowlabs.grpc_async;

public final class SparkNLP {
  private SparkNLP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_async_nlp_input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_async_nlp_input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_async_nlp_output_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_async_nlp_output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020definition.proto\022\ngrpc_async\"\031\n\tnlp_in" +
      "put\022\014\n\004text\030\001 \001(\t\"\034\n\nnlp_output\022\016\n\006resul" +
      "t\030\001 \001(\t2\317\005\n\016sparknlp_async\022;\n\006clf_1m\022\025.g" +
      "rpc_async.nlp_input\032\026.grpc_async.nlp_out" +
      "put\"\0000\001\022<\n\007clf_10m\022\025.grpc_async.nlp_inpu" +
      "t\032\026.grpc_async.nlp_output\"\0000\001\022=\n\010clf_100" +
      "m\022\025.grpc_async.nlp_input\032\026.grpc_async.nl" +
      "p_output\"\0000\001\022=\n\010clf_200m\022\025.grpc_async.nl" +
      "p_input\032\026.grpc_async.nlp_output\"\0000\001\022=\n\010c" +
      "lf_300m\022\025.grpc_async.nlp_input\032\026.grpc_as" +
      "ync.nlp_output\"\0000\001\022>\n\tclfner_1m\022\025.grpc_a" +
      "sync.nlp_input\032\026.grpc_async.nlp_output\"\000" +
      "0\001\022>\n\tdocclf_1m\022\025.grpc_async.nlp_input\032\026" +
      ".grpc_async.nlp_output\"\0000\001\022?\n\ndocclf_10m" +
      "\022\025.grpc_async.nlp_input\032\026.grpc_async.nlp" +
      "_output\"\0000\001\022@\n\013docclf_100m\022\025.grpc_async." +
      "nlp_input\032\026.grpc_async.nlp_output\"\0000\001\022@\n" +
      "\013docclf_200m\022\025.grpc_async.nlp_input\032\026.gr" +
      "pc_async.nlp_output\"\0000\001\022@\n\013docclf_300m\022\025" +
      ".grpc_async.nlp_input\032\026.grpc_async.nlp_o" +
      "utput\"\0000\001B/\n\033com.johnsnowlabs.grpc_async" +
      "B\010SparkNLPP\001\242\002\003NLPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_async_nlp_input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_async_nlp_input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_async_nlp_input_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_grpc_async_nlp_output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_async_nlp_output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_async_nlp_output_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
