![JohnSnowLabs](https://nlp.johnsnowlabs.com/assets/images/logo.png)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/11.Pretrained_Clinical_Pipelines.ipynb)

# 11. Pretrained_Clinical_Pipelines

## Colab Setup

In [ ]:
import json

from google.colab import files

license_keys = files.upload()

with open(list(license_keys.keys())[0]) as f:
    license_keys = json.load(f)

In [2]:
%%capture
for k,v in license_keys.items(): 
    %set_env $k=$v

!wget https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/jsl_colab_setup.sh
!bash jsl_colab_setup.sh -p 2.4.4

In [3]:
import json
import os
from pyspark.ml import Pipeline
from pyspark.sql import SparkSession

from sparknlp.annotator import *
from sparknlp_jsl.annotator import *
from sparknlp.base import *
import sparknlp_jsl
import sparknlp

params = {"spark.driver.memory":"16G",
"spark.kryoserializer.buffer.max":"2000M",
"spark.driver.maxResultSize":"2000M"}

spark = sparknlp_jsl.start(license_keys['SECRET'],params=params)

print ("Spark NLP Version :", sparknlp.version())
print ("Spark NLP_JSL Version :", sparknlp_jsl.version())

Spark NLP Version : 2.7.4
Spark NLP_JSL Version : 2.7.6



<b>  if you want to work with Spark 2.3 </b>
```
import os

# Install java
! apt-get update -qq
! apt-get install -y openjdk-8-jdk-headless -qq > /dev/null

!wget -q https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz

!tar xf spark-2.3.0-bin-hadoop2.7.tgz
!pip install -q findspark

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
os.environ["SPARK_HOME"] = "/content/spark-2.3.0-bin-hadoop2.7"
! java -version

import findspark
findspark.init()
from pyspark.sql import SparkSession

! pip install --ignore-installed -q spark-nlp==2.7.5
import sparknlp

spark = sparknlp.start(spark23=True)
```

## Pretrained Pipelines

In order to save you from creating a pipeline from scratch, Spark NLP also has a pre-trained pipelines that are already fitted using certain annotators and transformers according to various use cases.

Here is the list of clinical pre-trained pipelines: 

> These clinical pipelines are trained with `embeddings_healthcare_100d` and accuracies might be 1-2% lower than `embeddings_clinical` which is 200d.

**1.   explain_clinical_doc_carp** :

> a pipeline with `ner_clinical`, `assertion_dl`, `re_clinical` and `ner_posology`. It will extract clinical and medication entities, assign assertion status and find relationships between clinical entities.

**2.   explain_clinical_doc_era** :

> a pipeline with `ner_clinical_events`, `assertion_dl` and `re_temporal_events_clinical`. It will extract clinical entities, assign assertion status and find temporal relationships between clinical entities.

**3.   recognize_entities_posology** :

> a pipeline with `ner_posology`. It will only extract medication entities.


** Since 3rd pipeline is already a subset of 1st and 2nd pipeline, we will only cover the first two pipelines in this notebook.

**4.   explain_clinical_doc_ade** :

> a pipeline for `Adverse Drug Events (ADE)` with `ner_ade_biobert`, `assertiondl_biobert` and `classifierdl_ade_conversational_biobert`. It will extract `ADE` and `DRUG` clinical entities, assign assertion status to `ADE` entities, and then assign ADE status to a text (`True` means ADE, `False` means not related to ADE).

**letter codes in the naming conventions:**

> c : ner_clinical

> e : ner_clinical_events

> r : relation extraction

> p : ner_posology

> a : assertion

> ade : adverse drug events

**Relation Extraction types:**

`re_clinical` >> TrIP (improved), TrWP (worsened), TrCP (caused problem), TrAP (administered), TrNAP (avoided), TeRP (revealed problem), TeCP (investigate problem), PIP (problems related)

`re_temporal_events_clinical` >> `AFTER`, `BEFORE`, `OVERLAP`


## 1.explain_clinical_doc_carp 

a pipeline with ner_clinical, assertion_dl, re_clinical and ner_posology. It will extract clinical and medication entities, assign assertion status and find relationships between clinical entities.

In [ ]:
from sparknlp.pretrained import PretrainedPipeline

In [ ]:
pipeline = PretrainedPipeline('explain_clinical_doc_carp', 'en', 'clinical/models')

explain_clinical_doc_carp download started this may take some time.
Approx size to download 526.5 MB
[OK!]


In [ ]:
pipeline.model.stages

[DocumentAssembler_8aeb50463a0d,
 SentenceDetector_635a56ed49ab,
 REGEX_TOKENIZER_6f0bd3b85024,
 WORD_EMBEDDINGS_MODEL_a5c1afb0b657,
 POS_be8d41751649,
 NerDLModel_706522935b2e,
 NerConverter_b818c367ba56,
 dependency_68159e3d6dac,
 NerDLModel_01b90ff03d9e,
 NerConverter_335d7d4208fc,
 RelationExtractionModel_0a71121bf321,
 ASSERTION_DL_941a00a50db4]

In [ ]:
# Load pretrained pipeline from local disk:

# >> pipeline_local = PretrainedPipeline.from_disk('/root/cache_pretrained/explain_clinical_doc_carp_en_2.5.5_2.4_1597841630062')

In [ ]:
text ="""A 28-year-old female with a history of gestational diabetes mellitus, used to take metformin 1000 mg two times a day, presented with a one-week history of polyuria , polydipsia , poor appetite , and vomiting .
She was seen by the endocrinology service and discharged on 40 units of insulin glargine at night, 12 units of insulin lispro with meals.
"""

annotations = pipeline.annotate(text)

annotations.keys()


dict_keys(['sentences', 'clinical_ner_tags', 'document', 'ner_chunks', 'clinical_ner_chunks', 'ner_tags', 'assertion', 'clinical_relations', 'tokens', 'embeddings', 'pos_tags', 'dependencies'])

In [ ]:
import pandas as pd

rows = list(zip(annotations['tokens'], annotations['clinical_ner_tags'], annotations['ner_tags'], annotations['pos_tags'], annotations['dependencies']))

df = pd.DataFrame(rows, columns = ['tokens','clinical_ner_tags','posology_ner_tags','POS_tags','dependencies'])

df.head(20)

tokens clinical_ner_tags posology_ner_tags POS_tags dependencies
0             A                 O                 O       DD       female
1   28-year-old                 O                 O       NN       female
2        female                 O                 O       NN         ROOT
3          with                 O                 O       II      history
4             a                 O                 O       DD      history
5       history                 O                 O       NN       female
6            of                 O                 O       II      history
7   gestational         B-PROBLEM                 O       JJ           of
8      diabetes         I-PROBLEM                 O       NN     mellitus
9      mellitus         I-PROBLEM                 O       NN  gestational
10            ,                 O                 O       NN         used
11         used                 O                 O      VVN     mellitus
12           to                 O                 O       TO         take
13         take                 O                 O      VVI         used
14    metformin       B-TREATMENT            B-Drug       NN         take
15         1000                 O        B-Strength       MC    metformin
16           mg                 O        I-Strength       NN         1000
17          two                 O       B-Frequency       MC        times
18        times                 O       I-Frequency      NNS           mg
19            a                 O       I-Frequency       DD          day

In [ ]:
text = 'Patient has a headache for the last 2 weeks and appears anxious when she walks fast. No alopecia noted. She denies pain'

result = pipeline.fullAnnotate(text)[0]

chunks=[]
entities=[]
status=[]

for n,m in zip(result['clinical_ner_chunks'],result['assertion']):
    
    chunks.append(n.result)
    entities.append(n.metadata['entity']) 
    status.append(m.result)
        
df = pd.DataFrame({'chunks':chunks, 'entities':entities, 'assertion':status})

df

chunks entities assertion
0  a headache  PROBLEM   present
1     anxious  PROBLEM   present
2    alopecia  PROBLEM    absent
3        pain  PROBLEM    absent

In [ ]:
text = """
The patient was prescribed 1 unit of Advil for 5 days after meals. The patient was also 
given 1 unit of Metformin daily.
He was seen by the endocrinology service and she was discharged on 40 units of insulin glargine at night , 
12 units of insulin lispro with meals , and metformin 1000 mg two times a day.
"""

result = pipeline.fullAnnotate(text)[0]

chunks=[]
entities=[]
begins=[]
ends=[]

for n in result['ner_chunks']:
    
    chunks.append(n.result)
    begins.append(n.begin)
    ends.append(n.end)
    entities.append(n.metadata['entity']) 
        
df = pd.DataFrame({'chunks':chunks, 'begin':begins, 'end':ends, 'entities':entities})

df

chunks  begin  end   entities
0             1 unit     28   33     Dosage
1              Advil     38   42       Drug
2         for 5 days     44   53   Duration
3             1 unit     96  101     Dosage
4          Metformin    106  114       Drug
5              daily    116  120  Frequency
6           40 units    190  197     Dosage
7   insulin glargine    202  217       Drug
8           at night    219  226  Frequency
9           12 units    231  238     Dosage
10    insulin lispro    243  256       Drug
11        with meals    258  267  Frequency
12         metformin    275  283       Drug
13           1000 mg    285  291   Strength
14   two times a day    293  307  Frequency

In [ ]:
import pandas as pd

def get_relations_df (results, col='relations'):
  rel_pairs=[]
  for rel in results[0][col]:
      rel_pairs.append((
          rel.result, 
          rel.metadata['entity1'], 
          rel.metadata['entity1_begin'],
          rel.metadata['entity1_end'],
          rel.metadata['chunk1'], 
          rel.metadata['entity2'],
          rel.metadata['entity2_begin'],
          rel.metadata['entity2_end'],
          rel.metadata['chunk2'], 
          rel.metadata['confidence']
      ))

  rel_df = pd.DataFrame(rel_pairs, columns=['relation','entity1','entity1_begin','entity1_end','chunk1','entity2','entity2_begin','entity2_end','chunk2', 'confidence'])

  rel_df.confidence = rel_df.confidence.astype(float)
  
  return rel_df


In [ ]:
text ="""A 28-year-old female with a history of gestational diabetes mellitus, used to take metformin 1000 mg two times a day, presented with a one-week history of polyuria , polydipsia , poor appetite , and vomiting .
She was seen by the endocrinology service and discharged on 40 units of insulin glargine at night, 12 units of insulin lispro with meals.
"""

annotations = pipeline.fullAnnotate(text)

rel_df = get_relations_df (annotations, 'clinical_relations')

rel_df

relation  entity1 entity1_begin  ... entity2_end         chunk2 confidence
0     TrAP  PROBLEM            39  ...          91      metformin   0.999896
1     TrCP  PROBLEM           155  ...         175     polydipsia   0.647005
2     TrCP  PROBLEM           155  ...         191  poor appetite   0.909743
3     TrWP  PROBLEM           155  ...         206       vomiting   0.524460
4     TrCP  PROBLEM           166  ...         191  poor appetite   0.644446
5     TrAP  PROBLEM           166  ...         206       vomiting   0.503557
6     TrAP  PROBLEM           179  ...         206       vomiting   0.993527

[7 rows x 10 columns]

In [ ]:
text ="""
he patient was initially admitted for starvation ketosis , as she reported poor oral intake for three days prior to admission . 
However , serum chemistry obtained six hours after presentation revealed her glucose was 186 mg/dL , the anion gap was still elevated at 21 , serum bicarbonate was 16 mmol/L , triglyceride level peaked at 2050 mg/dL , and lipase was 52 U/L . The β-hydroxybutyrate level was obtained and found to be elevated at 5.29 mmol/L - the original sample was centrifuged and the chylomicron layer removed prior to analysis due to interference from turbidity caused by lipemia again . The patient was treated with an insulin drip for euDKA and HTG with a reduction in the anion gap to 13 and triglycerides to 1400 mg/dL , within 24 hours . Her euDKA was thought to be precipitated by her respiratory tract infection in the setting of SGLT2 inhibitor use . The patient was seen by the endocrinology service and she was discharged on 40 units of insulin glargine at night , 12 units of insulin lispro with meals , and metformin 1000 mg two times a day . It was determined that all SGLT2 inhibitors should be discontinued indefinitely . 
"""

annotations = pipeline.fullAnnotate(text)

rel_df = get_relations_df (annotations, 'clinical_relations')

rel_df[rel_df.confidence>0.9]


relation    entity1  ...                        chunk2 confidence
2      TrAP    PROBLEM  ...             serum bicarbonate   0.997434
3      TrAP    PROBLEM  ...                        lipase   0.996670
4      TrAP    PROBLEM  ...                           U/L   0.939070
6      TrIP       TEST  ...                           U/L   0.926109
8      TrAP       TEST  ...                           U/L   0.999179
10     TrAP    PROBLEM  ...         the chylomicron layer   0.999306
12     TrAP  TREATMENT  ...                           HTG   0.999923
13     TrAP       TEST  ...  a reduction in the anion gap   0.998082
14     TrAP       TEST  ...                 triglycerides   0.955180
15     TrAP    PROBLEM  ...                 triglycerides   0.947221

[10 rows x 10 columns]

## **2.   explain_clinical_doc_era** 

> a pipeline with `ner_clinical_events`, `assertion_dl` and `re_temporal_events_clinical`. It will extract clinical entities, assign assertion status and find temporal relationships between clinical entities.



In [ ]:
era_pipeline = PretrainedPipeline('explain_clinical_doc_era', 'en', 'clinical/models')

explain_clinical_doc_era download started this may take some time.
Approx size to download 512.8 MB
[OK!]


In [ ]:
era_pipeline.model.stages

[DocumentAssembler_f548f799ea2a,
 SentenceDetector_249f783c340c,
 REGEX_TOKENIZER_209534c638ca,
 POS_be8d41751649,
 dependency_68159e3d6dac,
 WORD_EMBEDDINGS_MODEL_a5c1afb0b657,
 NerDLModel_3c27190d1858,
 NerConverter_9fff8fa39dbd,
 RelationExtractionModel_fb3be959a99e,
 NerConverter_50212b459b4b,
 ASSERTION_DL_941a00a50db4]

In [ ]:
text ="""She is admitted to The John Hopkins Hospital 2 days ago with a history of gestational diabetes mellitus diagnosed. She denied pain and any headache.
She was seen by the endocrinology service and she was discharged on 03/02/2018 on 40 units of insulin glargine, 
12 units of insulin lispro, and metformin 1000 mg two times a day. She had close follow-up with endocrinology post discharge. 
"""

result = era_pipeline.fullAnnotate(text)[0]


In [ ]:
result.keys()

dict_keys(['sentences', 'clinical_ner_tags', 'clinical_ner_chunks_re', 'document', 'clinical_ner_chunks', 'assertion', 'clinical_relations', 'tokens', 'embeddings', 'pos_tags', 'dependencies'])

In [ ]:
import pandas as pd

chunks=[]
entities=[]
begins=[]
ends=[]

for n in result['clinical_ner_chunks']:
    
    chunks.append(n.result)
    begins.append(n.begin)
    ends.append(n.end)
    entities.append(n.metadata['entity']) 
        
df = pd.DataFrame({'chunks':chunks, 'begin':begins, 'end':ends, 'entities':entities})

df

chunks  begin  end       entities
0                        admitted      7   14     OCCURRENCE
1       The John Hopkins Hospital     19   43  CLINICAL_DEPT
2                      2 days ago     45   54           DATE
3   gestational diabetes mellitus     74  102        PROBLEM
4                       diagnosed    104  112     OCCURRENCE
5                          denied    119  124     EVIDENTIAL
6                            pain    126  129        PROBLEM
7                    any headache    135  146        PROBLEM
8                            seen    157  160     OCCURRENCE
9       the endocrinology service    165  189  CLINICAL_DEPT
10                     discharged    203  212     OCCURRENCE
11                     03/02/2018    217  226           DATE
12               insulin glargine    243  258      TREATMENT
13                 insulin lispro    274  287      TREATMENT
14                      metformin    294  302      TREATMENT
15                two times a day    312  326      FREQUENCY
16                close follow-up    337  351     OCCURRENCE
17                  endocrinology    358  370  CLINICAL_DEPT
18                      discharge    377  385     OCCURRENCE

In [ ]:
chunks=[]
entities=[]
status=[]

for n,m in zip(result['clinical_ner_chunks'],result['assertion']):
    
    chunks.append(n.result)
    entities.append(n.metadata['entity']) 
    status.append(m.result)
        
df = pd.DataFrame({'chunks':chunks, 'entities':entities, 'assertion':status})

df

chunks       entities assertion
0                        admitted     OCCURRENCE   present
1       The John Hopkins Hospital  CLINICAL_DEPT   present
2                      2 days ago           DATE   present
3   gestational diabetes mellitus        PROBLEM   present
4                       diagnosed     OCCURRENCE    absent
5                          denied     EVIDENTIAL    absent
6                            pain        PROBLEM    absent
7                    any headache        PROBLEM   present
8                            seen     OCCURRENCE   present
9       the endocrinology service  CLINICAL_DEPT   present
10                     discharged     OCCURRENCE   present
11                     03/02/2018           DATE   present
12               insulin glargine      TREATMENT   present
13                 insulin lispro      TREATMENT   present
14                      metformin      TREATMENT   present
15                two times a day      FREQUENCY   present

In [ ]:
annotations = era_pipeline.fullAnnotate(text)

rel_df = get_relations_df (annotations, 'clinical_relations')

rel_df


relation        entity1  ...                         chunk2 confidence
0     AFTER     OCCURRENCE  ...      The John Hopkins Hospital   1.000000
1   OVERLAP  CLINICAL_DEPT  ...  gestational diabetes mellitus   0.990721
2    BEFORE        PROBLEM  ...                      diagnosed   1.000000
3    BEFORE     EVIDENTIAL  ...                           pain   1.000000
4   OVERLAP     EVIDENTIAL  ...                   any headache   0.998176
5   OVERLAP        PROBLEM  ...                   any headache   1.000000
6   OVERLAP     OCCURRENCE  ...      the endocrinology service   1.000000
7     AFTER     OCCURRENCE  ...                     discharged   1.000000
8     AFTER     OCCURRENCE  ...                     03/02/2018   0.999092
9     AFTER     OCCURRENCE  ...                 insulin lispro   0.996928
10    AFTER  CLINICAL_DEPT  ...                     discharged   0.810061
11  OVERLAP  CLINICAL_DEPT  ...                     03/02/2018   0.999997
12  OVERLAP     OCCURRENCE  ...                     03/02/2018   1.000000
13    AFTER     OCCURRENCE  ...               insulin glargine   0.998801
14    AFTER     OCCURRENCE  ...                 insulin lispro   0.999772
15  OVERLAP           DATE  ...               insulin glargine   1.000000
16  OVERLAP           DATE  ...                 insulin lispro   1.000000
17  OVERLAP      TREATMENT  ...                two times a day   1.000000
18  OVERLAP     OCCURRENCE  ...                  endocrinology   1.000000
19    AFTER     OCCURRENCE  ...                      discharge   0.874858
20    AFTER  CLINICAL_DEPT  ...                      discharge   1.000000

[21 rows x 10 columns]

In [ ]:
annotations[0]['clinical_relations']

[Annotation(category, 7, 43, AFTER, {'chunk2': 'The John Hopkins Hospital', 'confidence': '1.0', 'entity2_end': '43', 'chunk1': 'admitted', 'entity2_begin': '19', 'entity1': 'OCCURRENCE', 'entity1_begin': '7', 'entity1_end': '14', 'entity2': 'CLINICAL_DEPT'}),
 Annotation(category, 19, 102, OVERLAP, {'chunk2': 'gestational diabetes mellitus', 'confidence': '0.9907205', 'entity2_end': '102', 'chunk1': 'The John Hopkins Hospital', 'entity2_begin': '74', 'entity1': 'CLINICAL_DEPT', 'entity1_begin': '19', 'entity1_end': '43', 'entity2': 'PROBLEM'}),
 Annotation(category, 74, 112, BEFORE, {'chunk2': 'diagnosed', 'confidence': '1.0', 'entity2_end': '112', 'chunk1': 'gestational diabetes mellitus', 'entity2_begin': '104', 'entity1': 'PROBLEM', 'entity1_begin': '74', 'entity1_end': '102', 'entity2': 'OCCURRENCE'}),
 Annotation(category, 119, 129, BEFORE, {'chunk2': 'pain', 'confidence': '1.0', 'entity2_end': '129', 'chunk1': 'denied', 'entity2_begin': '126', 'entity1': 'EVIDENTIAL', 'entity1_b

## 3.explain_clinical_doc_ade 

A pipeline for `Adverse Drug Events (ADE)` with `ner_ade_healthcare`, and `classifierdl_ade_biobert`. It will extract `ADE` and `DRUG` clinical entities, and then assign ADE status to a text(`Negative` means ADE, `Neutral` means not related to ADE).

In [ ]:
ade_pipeline = PretrainedPipeline('explain_clinical_doc_ade', 'en', 'clinical/models')

explain_clinical_doc_ade download started this may take some time.
Approx size to download 426.7 MB
[OK!]


In [ ]:
ade_pipeline.fullAnnotate("I feel a bit drowsy & have a little blurred vision, so far no gastric problems.")[0]['class'][0].metadata

{'sentence': '0', 'False': '0.01119729', 'True': '0.98880273'}

In [ ]:
text = "I feel a bit drowsy & have a little blurred vision, so far no gastric problems. I have been on Arthrotec 50 for over 10 years on and off, only taking it when I needed it. Due to my arthritis getting progressively worse, to the point where I am in tears with the agony, gp's started me on 75 twice a day and I have to take it every day for the next month to see how I get on, here goes. So far its been very good, pains almost gone, but I feel a bit weird, didn't have that when on 50."

import pandas as pd

chunks = []
entities = []
begin =[]
end = []

print ('sentence:', text)
print()

result = ade_pipeline.fullAnnotate(text)

print ('ADE status:', result[0]['class'][0].result)

print ('prediction probability>> True : ', result[0]['class'][0].metadata['True'], \
        'False: ', result[0]['class'][0].metadata['False'])

for n in result[0]['ner_chunk']:

    begin.append(n.begin)
    end.append(n.end)
    chunks.append(n.result)
    entities.append(n.metadata['entity']) 

df = pd.DataFrame({'chunks':chunks, 'entities':entities,
                'begin': begin, 'end': end})

df


sentence: I feel a bit drowsy & have a little blurred vision, so far no gastric problems. I have been on Arthrotec 50 for over 10 years on and off, only taking it when I needed it. Due to my arthritis getting progressively worse, to the point where I am in tears with the agony, gp's started me on 75 twice a day and I have to take it every day for the next month to see how I get on, here goes. So far its been very good, pains almost gone, but I feel a bit weird, didn't have that when on 50.

ADE status: True
prediction probability>> True :  0.9920334 False:  0.007966584


chunks entities  begin  end
0             bit drowsy      ADE      9   18
1  little blurred vision      ADE     29   49
2       gastric problems      ADE     62   77
3              Arthrotec     DRUG     95  103
4       feel a bit weird      ADE    438  453

#### with AssertionDL

In [ ]:
import pandas as pd

text = 'I was on Voltaren for about 4 years and all of the sudden had a minor stroke and had blood clots that traveled to my eye. I had every test in the book done at the hospital, and they couldnt find anything. I was completley healthy! I am thinking it was from the voltaren. I have been off of the drug for 8 months now, and have never felt better. I started eating healthy and working out and that has help alot. I can now sleep all thru the night. I wont take this again. If I have the back pain, I will pop a tylonol instead.'

print (text)

light_result = ade_pipeline.fullAnnotate(text)[0]

chunks=[]
entities=[]
status=[]

for n,m in zip(light_result['ass_ner_chunk'],light_result['assertion']):
    
    chunks.append(n.result)
    entities.append(n.metadata['entity']) 
    status.append(m.result)
        
df = pd.DataFrame({'chunks':chunks, 'entities':entities, 'assertion':status})

df

I was on Voltaren for about 4 years and all of the sudden had a minor stroke and had blood clots that traveled to my eye. I had every test in the book done at the hospital, and they couldnt find anything. I was completley healthy! I am thinking it was from the voltaren. I have been off of the drug for 8 months now, and have never felt better. I started eating healthy and working out and that has help alot. I can now sleep all thru the night. I wont take this again. If I have the back pain, I will pop a tylonol instead.


chunks entities assertion
0                             Voltaren     DRUG   present
1                               stroke      ADE   present
2  blood clots that traveled to my eye      ADE   present
3                             voltaren     DRUG   present

## 4.ICD10CM to Snomed Code

This pretrained pipeline maps ICD10CM codes to SNOMED codes without using any text data. You’ll just feed a comma or white space delimited ICD10CM codes and it will return the corresponding SNOMED codes as a list. For the time being, it supports 132K Snomed codes and will be augmented & enriched in the next releases.

In [ ]:
icd_snomed_pipeline = PretrainedPipeline("icd10cm_snomed_mapping", "en", "clinical/models")

In [ ]:
icd_snomed_pipeline.model.stages

[DocumentAssembler_e31d34ad0ead,
 REGEX_TOKENIZER_b99851bd101f,
 LEMMATIZER_0ca0f7005a90,
 Finisher_fcdbc12949ba]

In [ ]:
icd_snomed_pipeline.annotate('M89.50 I288 H16269')

{'icd10cm': ['M89.50', 'I288', 'H16269'],
 'snomed': ['733187009', '449433008', '51264003']}

**ICD10CM ---------- Details** 

M89.50 -----------------  Osteolysis, unspecified site  
I288 ----------------------  Other diseases of pulmonary vessels  
H16269 ----------------  Vernal keratoconjunctivitis, with limbar and corneal involvement, unspecified eye  

**SNOMED ----------- Details**  

733187009 ---------- Osteolysis following surgical procedure on skeletal system  
449433008 ---------- Diffuse stenosis of left pulmonary artery  
51264003 ------------ Limbal AND/OR corneal involvement in vernal conjunctivitis

## 5.Snomed to ICD10CM Code
This pretrained pipeline maps SNOMED codes to ICD10CM codes without using any text data. You'll just feed a comma or white space delimited SNOMED codes and it will return the corresponding candidate ICD10CM codes as a list (multiple ICD10 codes for each Snomed code). For the time being, it supports 132K Snomed codes and 30K ICD10 codes and will be augmented & enriched in the next releases.

In [ ]:
snomed_icd_pipeline = PretrainedPipeline("snomed_icd10cm_mapping","en","clinical/models")

In [ ]:
snomed_icd_pipeline.model.stages

[DocumentAssembler_e31d34ad0ead,
 REGEX_TOKENIZER_1eddb70ad03b,
 LEMMATIZER_e9ae88d69d05,
 Finisher_253e42d00101]

In [ ]:
snomed_icd_pipeline.annotate('733187009 449433008 51264003')

{'icd10cm': ['M89.59, M89.50, M96.89',
  'Q25.6, I28.8',
  'H10.45, H10.1, H16.269'],
 'snomed': ['733187009', '449433008', '51264003']}


**SNOMED ----------- Details**  

733187009 ---------- Osteolysis following surgical procedure on skeletal system  
449433008 ---------- Diffuse stenosis of left pulmonary artery  
51264003 ------------ Limbal AND/OR corneal involvement in vernal conjunctivitis  


**ICDM10CM -------- Details**  

M89.59 ------------------	Osteolysis, multiple sites  
M89.50 ------------------ Osteolysis, unspecified site  
M96.89 ------------------ Other intraoperative and postprocedural complications and disorders of the musculoskeletal system  

Q25.6 ---------------------	Stenosis of pulmonary artery    
I28.8 ---------------------- Other diseases of pulmonary vessels  

H10.45 ------------------- Other chronic allergic conjunctivitis  
H10.1 --------------------- Acute atopic conjunctivitis  
H16.269 ----------------- Vernal keratoconjunctivitis, with limbar and corneal involvement, unspecified eye
  