# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65\x66inition.proto\x12\nrouteguide\"\x19\n\tnlp_input\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\nnlp_output\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb1\x01\n\x08SparkNLP\x12\x36\n\x03\x63lf\x12\x15.routeguide.nlp_input\x1a\x16.routeguide.nlp_output\"\x00\x12\x36\n\x03ner\x12\x15.routeguide.nlp_input\x1a\x16.routeguide.nlp_output\"\x00\x12\x35\n\x02re\x12\x15.routeguide.nlp_input\x1a\x16.routeguide.nlp_output\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _NLP_INPUT._serialized_start=32
  _NLP_INPUT._serialized_end=57
  _NLP_OUTPUT._serialized_start=59
  _NLP_OUTPUT._serialized_end=87
  _SPARKNLP._serialized_start=90
  _SPARKNLP._serialized_end=267
# @@protoc_insertion_point(module_scope)
