![JohnSnowLabs](https://nlp.johnsnowlabs.com/assets/images/logo.png)

 [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings_JSL/Healthcare/13.1.Finetuning_Sentence_Entity_Resolver_Model.ipynb)

# 13.1 Finetuning Sentence Entity Resolver Model

In [ ]:
# Install the johnsnowlabs library to access Spark-OCR and Spark-NLP for Healthcare, Finance, and Legal.
! pip install -q johnsnowlabs 

In [ ]:
from google.colab import files
print('Please Upload your John Snow Labs License using the button below')
license_keys = files.upload()

In [ ]:
from johnsnowlabs import *

# After uploading your license run this to install all licensed Python Wheels and pre-download Jars the Spark Session JVM
nlp.install()

In [ ]:
from johnsnowlabs import *

# Automatically load license data and start a session with all jars user has access to
spark = nlp.start()

## Load Dataset

In [5]:
!wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Healthcare/data/AskAPatient.fold-0.train.txt

Now we will create a pandas dataframe using downloaded dataset, and then convert it to a spark dataframe.



In [6]:
import pandas as pd

cols = ["conceptId","_term","term"]

aap_tr = pd.read_csv("AskAPatient.fold-0.train.txt",sep="\t", encoding="ISO-8859-1",header=None)
aap_tr.columns = cols
aap_tr["conceptId"] = aap_tr.conceptId.apply(str)

In [7]:
aap_tr.head()

conceptId                    _term                     term
0         108367008     Dislocation of joint     Dislocation of joint
1  3384011000036100                Arthrotec                Arthrotec
2         166717003  Serum creatinine raised  Serum creatinine raised
3  3877011000036101                  Lipitor                  Lipitor
4         402234004              Foot eczema              Foot eczema

In [8]:
aap_train_sdf = spark.createDataFrame(aap_tr).drop_duplicates()
aap_train_sdf.show()

+-----------------+--------------------+--------------------+
|        conceptId|               _term|                term|
+-----------------+--------------------+--------------------+
|        161891005|            Backache|            backache|
|        418290006|             Itching|               itchy|
|         35489007|          Depression|very serious depr...|
|         10601006|  Pain in lower limb|        pain in legs|
|        386806002|  Impaired cognition|  Impaired cognition|
|        386807006|   Memory impairment| memory difficulties|
|         21499005|Feeling agitated ...|   Severe aggitation|
|        247373008|          Ankle pain|          ANKLE PAIN|
|        262286000|    Weight increased|Big weight gain i...|
|         36349006|        Burning pain|burning in back o...|
|         24184005|Finding of increa...|blood pressure ha...|
|        308921004|Neurological symptom|Neurological symptom|
|        279043006|     Pain in buttock|     Pain in buttock|
|       

In [9]:
aap_train_sdf.printSchema()

root
 |-- conceptId: string (nullable = true)
 |-- _term: string (nullable = true)
 |-- term: string (nullable = true)



In [10]:
aap_train_sdf.count()

4382

We will limit our dataframe for a faster training.

In [11]:
aap_train_sdf = aap_train_sdf.limit(1000)

Here, we will create a pipeline for adding an embeddings column to our spark dataframe.

In [12]:
documentAssembler = nlp.DocumentAssembler()\
    .setInputCol("_term")\
    .setOutputCol("ner_chunk")

bert_embeddings = nlp.BertSentenceEmbeddings.pretrained("sbiobert_base_cased_mli", "en", "clinical/models")\
    .setInputCols(["ner_chunk"])\
    .setOutputCol("bert_embeddings")\
    .setCaseSensitive(False)

snomed_emb_pipeline = nlp.Pipeline(stages = [
    documentAssembler,
    bert_embeddings])


snomed_emb_model = snomed_emb_pipeline.fit(aap_train_sdf)

snomed_data = snomed_emb_model.transform(aap_train_sdf)

sbiobert_base_cased_mli download started this may take some time.
Approximate size to download 384.3 MB
[OK!]


Here is the new training dataframe.

In [13]:
snomed_data.show()

+-----------------+--------------------+--------------------+--------------------+--------------------+
|        conceptId|               _term|                term|           ner_chunk|     bert_embeddings|
+-----------------+--------------------+--------------------+--------------------+--------------------+
|        161891005|            Backache|            backache|[{document, 0, 7,...|[{sentence_embedd...|
|        418290006|             Itching|               itchy|[{document, 0, 6,...|[{sentence_embedd...|
|         35489007|          Depression|very serious depr...|[{document, 0, 9,...|[{sentence_embedd...|
|         10601006|  Pain in lower limb|        pain in legs|[{document, 0, 17...|[{sentence_embedd...|
|        386806002|  Impaired cognition|  Impaired cognition|[{document, 0, 17...|[{sentence_embedd...|
|        386807006|   Memory impairment| memory difficulties|[{document, 0, 16...|[{sentence_embedd...|
|         21499005|Feeling agitated ...|   Severe aggitation|[{d

Now we can train our SNOMED Sentence Entity Resolver Model by using `SentenceEntityResolverApproach` .

In [14]:
bertExtractor = medical.SentenceEntityResolverApproach()\
  .setNeighbours(25)\
  .setThreshold(1000)\
  .setInputCols("bert_embeddings")\
  .setNormalizedCol("_term")\
  .setLabelCol("conceptId")\
  .setOutputCol('snomed_code')\
  .setDistanceFunction("EUCLIDIAN")\
  .setCaseSensitive(False)

%time snomed_model = bertExtractor.fit(snomed_data)

CPU times: user 652 ms, sys: 76.9 ms, total: 729 ms
Wall time: 1min 55s


In [15]:
# save if you will need that later
snomed_model.write().overwrite().save("sbiobertresolve_snomed_model")

Lets create a new dataset and re-train our model by using this new dataset.



In [16]:
aap_tr.head()

conceptId                    _term                     term
0         108367008     Dislocation of joint     Dislocation of joint
1  3384011000036100                Arthrotec                Arthrotec
2         166717003  Serum creatinine raised  Serum creatinine raised
3  3877011000036101                  Lipitor                  Lipitor
4         402234004              Foot eczema              Foot eczema

We need the same columns for training.

In [17]:
new_dataset = pd.DataFrame(columns=aap_tr.columns)
new_dataset

Empty DataFrame
Columns: [conceptId, _term, term]
Index: []

## Use Cases

Now we can add our concept_codes and terms to this new dataframe. In this example we wanted to show you some cases that you can see the success of re-training feature and used `XXXX` in the codes to get easily;

- Added new lines that they are close to version of them in the main dataset (`Dislocation of joint -> Dislocation New Term`).

- Changed the code of the terms in the main dataset (`Arthrotec`)

- Changed the positions of the words in the terms (`Serum creatinine raised -> Raised serum creatinine`)

- Added new terms to the dataset (`New Drug`, `athlete's foot`)

In [18]:
new_dataset.conceptId = ["XXXX67008", "XXXXXXXX00036100", "XXXXX7003", "XXXXXXXX00036101", "XXXXX4004"]
new_dataset._term = ["Dislocation New Term", "Arthrotec", "Raised serum creatinine", "New Drug", "athlete's foot"]
new_dataset.term = ["Dislocation New Term", "Arthrotec", "Raised serum creatinine", "New Drug", "athlete's foot"]
new_dataset

conceptId                    _term                     term
0         XXXX67008     Dislocation New Term     Dislocation New Term
1  XXXXXXXX00036100                Arthrotec                Arthrotec
2         XXXXX7003  Raised serum creatinine  Raised serum creatinine
3  XXXXXXXX00036101                 New Drug                 New Drug
4         XXXXX4004           athlete's foot           athlete's foot

We transformed our new dataframe by using `snomed_emb_model` and added new columns that we need for re-training.

In [19]:
new_snomed_data = snomed_emb_model.transform(spark.createDataFrame(new_dataset))
new_snomed_data.show()

+----------------+--------------------+--------------------+--------------------+--------------------+
|       conceptId|               _term|                term|           ner_chunk|     bert_embeddings|
+----------------+--------------------+--------------------+--------------------+--------------------+
|       XXXX67008|Dislocation New Term|Dislocation New Term|[{document, 0, 19...|[{sentence_embedd...|
|XXXXXXXX00036100|           Arthrotec|           Arthrotec|[{document, 0, 8,...|[{sentence_embedd...|
|       XXXXX7003|Raised serum crea...|Raised serum crea...|[{document, 0, 22...|[{sentence_embedd...|
|XXXXXXXX00036101|            New Drug|            New Drug|[{document, 0, 7,...|[{sentence_embedd...|
|       XXXXX4004|      athlete's foot|      athlete's foot|[{document, 0, 13...|[{sentence_embedd...|
+----------------+--------------------+--------------------+--------------------+--------------------+



Now we will re-train our main model with new dataset by using `.setPretrainedModelPath()` parameter. 

In [20]:
new_snomed_model = bertExtractor.setPretrainedModelPath("sbiobertresolve_snomed_model").fit(new_snomed_data)

In [21]:
# save if you need later

new_snomed_model.write().overwrite().save("new_sbiobertresolve_snomed_model")

Write a function to show the results more clearly.

In [22]:
pd.set_option('display.max_colwidth', 0)


def get_codes (lp, text, vocab='snomed_code'):
    
    full_light_result = lp.fullAnnotate(text)

    chunks = []
    codes = []
    begin = []
    end = []
    resolutions=[]
    all_distances =[]
    all_codes=[]
    all_cosines = []

    for chunk, code in zip(full_light_result[0]['ner_chunk'], full_light_result[0][vocab]):
            
        begin.append(chunk.begin)
        end.append(chunk.end)
        chunks.append(chunk.result)
        codes.append(code.result) 
        all_codes.append(code.metadata['all_k_results'].split(':::'))
        resolutions.append(code.metadata['all_k_resolutions'].split(':::'))
        all_distances.append(code.metadata['all_k_distances'].split(':::'))
        all_cosines.append(code.metadata['all_k_cosine_distances'].split(':::'))
        
    df = pd.DataFrame({'chunks':chunks, 'begin': begin, 'end':end, 'code':codes,'all_codes':all_codes, 
                       'resolutions':resolutions, 'all_distances':all_cosines})
        
    return df



## Test the New Model
We will create a pipeline that contains both of the models and check the results by using `LightPipeline`.

In [23]:
documentAssembler = nlp.DocumentAssembler()\
      .setInputCol("text")\
      .setOutputCol("ner_chunk")

sbert_embedder = nlp.BertSentenceEmbeddings.pretrained('sbiobert_base_cased_mli', 'en','clinical/models')\
      .setInputCols(["ner_chunk"])\
      .setOutputCol("sbert_embeddings")\
      .setCaseSensitive(False)

first_model = medical.SentenceEntityResolverModel.load("sbiobertresolve_snomed_model") \
      .setInputCols(["ner_chunk", "sbert_embeddings"]) \
      .setOutputCol("first_code")

second_model = medical.SentenceEntityResolverModel.load("new_sbiobertresolve_snomed_model") \
      .setInputCols(["ner_chunk", "sbert_embeddings"]) \
      .setOutputCol("second_code")


pipelineModel = nlp.PipelineModel(
    stages = [
        documentAssembler,
        sbert_embedder,
        first_model,
        second_model])

snomed_lp = nlp.LightPipeline(pipelineModel)


sbiobert_base_cased_mli download started this may take some time.
Approximate size to download 384.3 MB
[OK!]


Lets test our models with the terms that we added into the new dataset and the ones that comes from the main model (`Stomach ache` and `Pins and needles`).

In [24]:
chunk_list = ["Dislocation New Term", "Arthrotec", "Raised serum creatinine", "New Drug", "athlete's foot", "Stomach ache", "Pins and needles"]
chunk_list

['Dislocation New Term',
 'Arthrotec',
 'Raised serum creatinine',
 'New Drug',
 "athlete's foot",
 'Stomach ache',
 'Pins and needles']

In [25]:
from IPython.display import display

for chunk in chunk_list:

    print ('\n >>','/'*30, chunk, '/'*30, '\n')
    
    print('First Model Result:')
    display(get_codes (snomed_lp, chunk, vocab='first_code'))
    
    print('\n Second Model Result:')
    display(get_codes (snomed_lp, chunk, vocab='second_code'))


 >> ////////////////////////////// Dislocation New Term ////////////////////////////// 

First Model Result:


chunks  begin  end     code  \
0  Dislocation New Term  0      19   2764000   

                                                                                                                                                                                                                                        all_codes  \
0  [2764000, 125667009, 429513001, 415749005, 202855006, 414469009, 249966004, 14351000168102, 12441001, 4308002, 21288011000036105, 54981004, 698065002, 1806006, 34840004, 283902008, 419076005, 53523011000036100, 3530011000036104, 23056005]   

                                                                                                                                                                                                                                                                                                          resolutions  \
0  [Joint crepitus, Contusion, Rupture of Achilles tendon, Rupture of tendon, Lateral epicondylitis, Impending shock, Spasmodic movement, Seroquel, Epistaxis, Repetitive strain injury, diclofenac, Charleyhorse, Acid reflux, Eruption, Tendonitis, Has delayed recall, Allergic reaction, Diovan, Lopid, Sciatica]   

                                                                                                                                                      all_distances  
0  [0.2654, 0.2695, 0.3075, 0.3011, 0.3281, 0.3136, 0.3238, 0.3381, 0.3422, 0.3231, 0.3598, 0.3562, 0.3352, 0.3335, 0.3447, 0.3418, 0.3383, 0.3491, 0.3609, 0.3472]


 Second Model Result:


chunks  begin  end       code  \
0  Dislocation New Term  0      19   XXXX67008   

                                                                                                                                                                                                                                         all_codes  \
0  [XXXX67008, XXXXXXXX00036101, 2764000, 125667009, 429513001, 415749005, 202855006, 414469009, 249966004, 14351000168102, 12441001, 4308002, 21288011000036105, 54981004, 698065002, 1806006, 34840004, 283902008, 419076005, 53523011000036100]   

                                                                                                                                                                                                                                                                                                                         resolutions  \
0  [Dislocation New Term, New Drug, Joint crepitus, Contusion, Rupture of Achilles tendon, Rupture of tendon, Lateral epicondylitis, Impending shock, Spasmodic movement, Seroquel, Epistaxis, Repetitive strain injury, diclofenac, Charleyhorse, Acid reflux, Eruption, Tendonitis, Has delayed recall, Allergic reaction, Diovan]   

                                                                                                                                                      all_distances  
0  [0.0000, 0.2513, 0.2654, 0.2695, 0.3075, 0.3011, 0.3281, 0.3136, 0.3238, 0.3381, 0.3422, 0.3231, 0.3598, 0.3562, 0.3352, 0.3335, 0.3447, 0.3418, 0.3383, 0.3491]


 >> ////////////////////////////// Arthrotec ////////////////////////////// 

First Model Result:


chunks  begin  end              code  \
0  Arthrotec  0      8    3384011000036100   

                                                                                                                                                                                                                                                                         all_codes  \
0  [3384011000036100, 53215011000036102, 87715008, 53458011000036102, 32970011000036103, 54981004, 28551000168108, 53523011000036100, 3530011000036104, 3563011000036102, 3848011000036104, 35209006, 3904011000036106, 247472004, 3877011000036101, 77424011000036100, 271587009]   

                                                                                                                                                               resolutions  \
0  [Arthrotec, Advil, Aptyalism, Aleve, Toprol-XL, Charleyhorse, Voltaren, Diovan, Lopid, Zantac, Pravachol, Sensitivity, Zocor, Hives, Lipitor, ubidecarenone, Stiffness]   

                                                                                                                              all_distances  
0  [0.0000, 0.1731, 0.1846, 0.2122, 0.2298, 0.2309, 0.2299, 0.2319, 0.2448, 0.2475, 0.2498, 0.2400, 0.2558, 0.2527, 0.2582, 0.2748, 0.2505]


 Second Model Result:


chunks  begin  end              code  \
0  Arthrotec  0      8    XXXXXXXX00036100   

                                                                                                                                                                                                                                                                                all_codes  \
0  [XXXXXXXX00036100, 3384011000036100, 53215011000036102, 87715008, 53458011000036102, 32970011000036103, 54981004, 28551000168108, 53523011000036100, 3530011000036104, 3563011000036102, 3848011000036104, 35209006, 3904011000036106, 247472004, 3877011000036101, 77424011000036100]   

                                                                                                                                                               resolutions  \
0  [Arthrotec, Arthrotec, Advil, Aptyalism, Aleve, Toprol-XL, Charleyhorse, Voltaren, Diovan, Lopid, Zantac, Pravachol, Sensitivity, Zocor, Hives, Lipitor, ubidecarenone]   

                                                                                                                              all_distances  
0  [0.0000, 0.0000, 0.1731, 0.1846, 0.2122, 0.2298, 0.2309, 0.2299, 0.2319, 0.2448, 0.2475, 0.2498, 0.2400, 0.2558, 0.2527, 0.2582, 0.2748]


 >> ////////////////////////////// Raised serum creatinine ////////////////////////////// 

First Model Result:


chunks  begin  end       code  \
0  Raised serum creatinine  0      22   432352001   

                                                                                                                                                                            all_codes  \
0  [432352001, 166830008, 69791001, 51590001, 249477003, 42399005, 60728008, 166702002, 24184005, 40095003, 278528006, 34436003, 271737000, 124042003, 43498006, 59976005, 166643006]   

                                                                                                                                                                                                                                                                                                                                                               resolutions  \
0  [Increased creatine kinase level, Serum cholesterol raised, Increased venous pressure, Increased pressure, Increased thirst, Renal failure, Abdominal swelling, Raised serum calcium level, Finding of increased blood pressure, Renal injury, Facial swelling, Haematuria, Anaemia, Increased lipid, Body fluid retention, Increased belching, Liver enzymes abnormal]   

                                                                                                                              all_distances  
0  [0.1387, 0.1686, 0.1815, 0.1821, 0.1831, 0.1847, 0.1939, 0.2002, 0.2020, 0.2050, 0.2016, 0.2143, 0.2166, 0.2300, 0.2198, 0.2309, 0.2210]


 Second Model Result:


chunks  begin  end       code  \
0  Raised serum creatinine  0      22   XXXXX7003   

                                                                                                                                                                            all_codes  \
0  [XXXXX7003, 432352001, 166830008, 69791001, 51590001, 249477003, 42399005, 60728008, 166702002, 24184005, 40095003, 278528006, 34436003, 271737000, 124042003, 43498006, 59976005]   

                                                                                                                                                                                                                                                                                                                                                                resolutions  \
0  [Raised serum creatinine, Increased creatine kinase level, Serum cholesterol raised, Increased venous pressure, Increased pressure, Increased thirst, Renal failure, Abdominal swelling, Raised serum calcium level, Finding of increased blood pressure, Renal injury, Facial swelling, Haematuria, Anaemia, Increased lipid, Body fluid retention, Increased belching]   

                                                                                                                              all_distances  
0  [0.0000, 0.1387, 0.1686, 0.1815, 0.1821, 0.1831, 0.1847, 0.1939, 0.2002, 0.2020, 0.2050, 0.2016, 0.2143, 0.2166, 0.2300, 0.2198, 0.2309]


 >> ////////////////////////////// New Drug ////////////////////////////// 

First Model Result:


chunks  begin  end       code  \
0  New Drug  0      7    419511003   

                                                                                                                                                                                                                                                                                         all_codes  \
0  [419511003, 14351000168102, 271807003, 34839011000036106, 21885011000036105, 21839011000036103, 21821011000036104, 77424011000036100, 21747011000036106, 1806006, 21252011000036100, 118940003, 21304011000036105, 21134002, 21288011000036105, 21659011000036107, 21930011000036101, 95319004]   

                                                                                                                                                                                                                                             resolutions  \
0  [Propensity to adverse reactions to drug, Seroquel, Rash, pethidine, ibuprofen, bisoprolol, codeine, ubidecarenone, glipizide, Eruption, morphine, Disorder of nervous system, naproxen, Disability, diclofenac, gemfibrozil, ezetimibe, Skin nodule]   

                                                                                                                                      all_distances  
0  [0.3044, 0.3488, 0.3267, 0.3476, 0.3438, 0.3811, 0.3639, 0.3921, 0.3705, 0.3566, 0.3779, 0.3533, 0.3704, 0.3497, 0.3936, 0.3961, 0.3833, 0.3762]


 Second Model Result:


chunks  begin  end              code  \
0  New Drug  0      7    XXXXXXXX00036101   

                                                                                                                                                                                                                                                                                                            all_codes  \
0  [XXXXXXXX00036101, XXXX67008, 419511003, 14351000168102, 271807003, 34839011000036106, 21885011000036105, 21839011000036103, 21821011000036104, 77424011000036100, 21747011000036106, 1806006, 21252011000036100, 118940003, 21304011000036105, 21134002, 21288011000036105, 21659011000036107, 21930011000036101]   

                                                                                                                                                                                                                                                                resolutions  \
0  [New Drug, Dislocation New Term, Propensity to adverse reactions to drug, Seroquel, Rash, pethidine, ibuprofen, bisoprolol, codeine, ubidecarenone, glipizide, Eruption, morphine, Disorder of nervous system, naproxen, Disability, diclofenac, gemfibrozil, ezetimibe]   

                                                                                                                                              all_distances  
0  [0.0000, 0.2513, 0.3044, 0.3488, 0.3267, 0.3476, 0.3438, 0.3811, 0.3639, 0.3921, 0.3705, 0.3566, 0.3779, 0.3533, 0.3704, 0.3497, 0.3936, 0.3961, 0.3833]


 >> ////////////////////////////// athlete's foot ////////////////////////////// 

First Model Result:


chunks  begin  end       code  \
0  athlete's foot  0      13   118932009   

                                                                                                                                                                                            all_codes  \
0  [118932009, 699368004, 128605003, 309087008, 298241001, 297142003, 102551008, 425772008, 6389006, 3253007, 22325002, 54981004, 16973004, 82971005, 387603000, 55260003, 3877011000036101, 8510008]   

                                                                                                                                                                                                                                                                                                                                   resolutions  \
0  [Disorder of foot, Symptom of ankle, Disorder of extremity, Paraesthesia of foot, Foot joint stiff, Foot swelling, Cramp in foot, Tendonitis of foot, Disturbance in physical behaviour, Discolouration of skin, Abnormal gait, Charleyhorse, Limping, Impaired mobility, Impairment of balance, Calcaneal spur, Lipitor, Reduced mobility]   

                                                                                                                                      all_distances  
0  [0.1275, 0.2012, 0.2001, 0.2106, 0.2076, 0.2152, 0.2178, 0.2278, 0.2248, 0.2374, 0.2402, 0.2601, 0.2451, 0.2423, 0.2451, 0.2645, 0.2647, 0.2546]


 Second Model Result:


chunks  begin  end       code  \
0  athlete's foot  0      13   XXXXX4004   

                                                                                                                                                                                              all_codes  \
0  [XXXXX4004, 118932009, 699368004, 128605003, 309087008, 298241001, 297142003, 102551008, 425772008, 6389006, 3253007, 22325002, 54981004, 16973004, 82971005, 387603000, 55260003, 3877011000036101]   

                                                                                                                                                                                                                                                                                                                                 resolutions  \
0  [athlete's foot, Disorder of foot, Symptom of ankle, Disorder of extremity, Paraesthesia of foot, Foot joint stiff, Foot swelling, Cramp in foot, Tendonitis of foot, Disturbance in physical behaviour, Discolouration of skin, Abnormal gait, Charleyhorse, Limping, Impaired mobility, Impairment of balance, Calcaneal spur, Lipitor]   

                                                                                                                                      all_distances  
0  [0.0000, 0.1275, 0.2012, 0.2001, 0.2106, 0.2076, 0.2152, 0.2178, 0.2278, 0.2248, 0.2374, 0.2402, 0.2601, 0.2451, 0.2423, 0.2451, 0.2645, 0.2647]


 >> ////////////////////////////// Stomach ache ////////////////////////////// 

First Model Result:


chunks  begin  end       code  \
0  Stomach ache  0      11   271681002   

                                                                                                              all_codes  \
0  [271681002, 162059005, 116289008, 16331000, 119416008, 21522001, 162043005, 82991003, 248490000, 36349006, 25064002]   

                                                                                                                                                                               resolutions  \
0  [Stomach ache, Upset stomach, Abdominal bloating, Heartburn, Epigastric discomfort, Abdominal pain, Hunger pain, Generalised aches and pains, Bloating symptom, Burning pain, Headache]   

                                                                              all_distances  
0  [0.0000, 0.0699, 0.0826, 0.0854, 0.0902, 0.0915, 0.0919, 0.1028, 0.1087, 0.1092, 0.1102]


 Second Model Result:


chunks  begin  end       code  \
0  Stomach ache  0      11   271681002   

                                                                                                              all_codes  \
0  [271681002, 162059005, 116289008, 16331000, 119416008, 21522001, 162043005, 82991003, 248490000, 36349006, 25064002]   

                                                                                                                                                                               resolutions  \
0  [Stomach ache, Upset stomach, Abdominal bloating, Heartburn, Epigastric discomfort, Abdominal pain, Hunger pain, Generalised aches and pains, Bloating symptom, Burning pain, Headache]   

                                                                              all_distances  
0  [0.0000, 0.0699, 0.0826, 0.0854, 0.0902, 0.0915, 0.0919, 0.1028, 0.1087, 0.1092, 0.1102]


 >> ////////////////////////////// Pins and needles ////////////////////////////// 

First Model Result:


chunks  begin  end      code  \
0  Pins and needles  0      15   62507009   

                                                                                                              all_codes  \
0  [62507009, 37567005, 17971005, 247472004, 131148009, 91019004, 43498006, 417237009, 283050005, 161891005, 271807003]   

                                                                                                                                        resolutions  \
0  [Pins and needles, Acenaesthesia, Sedated, Hives, Bleeding, Paraesthesia, Body fluid retention, Blister, Abrasion of eye region, Backache, Rash]   

                                                                              all_distances  
0  [0.0000, 0.2716, 0.2708, 0.2917, 0.2857, 0.2918, 0.2834, 0.3023, 0.2994, 0.2994, 0.2969]


 Second Model Result:


chunks  begin  end      code  \
0  Pins and needles  0      15   62507009   

                                                                                                              all_codes  \
0  [62507009, 37567005, 17971005, 247472004, 131148009, 91019004, 43498006, 417237009, 283050005, 161891005, 271807003]   

                                                                                                                                        resolutions  \
0  [Pins and needles, Acenaesthesia, Sedated, Hives, Bleeding, Paraesthesia, Body fluid retention, Blister, Abrasion of eye region, Backache, Rash]   

                                                                              all_distances  
0  [0.0000, 0.2716, 0.2708, 0.2917, 0.2857, 0.2918, 0.2834, 0.3023, 0.2994, 0.2994, 0.2969]

### Conclusion
As you can see in the results;

- The resolutions of the new added terms are at the top of the results.

- The terms that we changed the concept_codes, are at the top of the resuls.

- The close terms results are resolved successfully.

- The terms that comes from the main dataset are resolved with the same result.

## Overriding Codes

We can override new codes over the existing codes if in pretrained Sentence Entity Resolver Model by using `.setOverrideExistingCodes(True)` . For example, you want to add a new term to a pretrained resolver model, and if the code of term already exists in the pretrained model, when you .setOverwriteExistingCode(True), it removes all the same codes and their descriptions from the model, then you will have just the new term with its code in the fine-tuned model.

In [26]:
snomed_data.show()

+-----------------+--------------------+--------------------+--------------------+--------------------+
|        conceptId|               _term|                term|           ner_chunk|     bert_embeddings|
+-----------------+--------------------+--------------------+--------------------+--------------------+
|        161891005|            Backache|            backache|[{document, 0, 7,...|[{sentence_embedd...|
|        418290006|             Itching|               itchy|[{document, 0, 6,...|[{sentence_embedd...|
|         35489007|          Depression|very serious depr...|[{document, 0, 9,...|[{sentence_embedd...|
|         10601006|  Pain in lower limb|        pain in legs|[{document, 0, 17...|[{sentence_embedd...|
|        386806002|  Impaired cognition|  Impaired cognition|[{document, 0, 17...|[{sentence_embedd...|
|        386807006|   Memory impairment| memory difficulties|[{document, 0, 16...|[{sentence_embedd...|
|         21499005|Feeling agitated ...|   Severe aggitation|[{d

In [27]:
display(get_codes (snomed_lp, "Backache", vocab='first_code'))

chunks  begin  end       code  \
0  Backache  0      7    161891005   

                                                                                         all_codes  \
0  [161891005, 279039007, 48926009, 404640003, 367391008, 16269008, 116289008, 81680005, 25064002]   

                                                                                                        resolutions  \
0  [Backache, Low back pain, Pain in spine, Dizziness, Malaise, Neuralgia, Abdominal bloating, Neck pain, Headache]   

                                                              all_distances  
0  [0.0000, 0.1411, 0.1410, 0.1426, 0.1517, 0.1569, 0.1520, 0.1530, 0.1571]

In [28]:
display(get_codes (snomed_lp, "toothache", vocab='first_code'))

chunks  begin  end       code  \
0  toothache  0      8    288939007   

                                               all_codes  \
0  [288939007, 404640003, 22253000, 161891005, 25064002]   

                                                    resolutions  \
0  [Difficulty swallowing, Dizziness, Pain, Backache, Headache]   

                              all_distances  
0  [0.1266, 0.1317, 0.1340, 0.1390, 0.1360]

Lets add a new term `chestache`has the same code with `Bachache`, `161891005` and `.setOverrideExistingCodes(True)`.

In [29]:
override_data = spark.createDataFrame(pd.DataFrame({"conceptId":["161891005"], "_term": ["toothache"], "term": ["toothache"]}))
override_data.show()

+---------+---------+---------+
|conceptId|    _term|     term|
+---------+---------+---------+
|161891005|toothache|toothache|
+---------+---------+---------+



In [30]:
override_data = snomed_emb_model.transform(override_data)
override_data.show()

+---------+---------+---------+--------------------+--------------------+
|conceptId|    _term|     term|           ner_chunk|     bert_embeddings|
+---------+---------+---------+--------------------+--------------------+
|161891005|toothache|toothache|[{document, 0, 8,...|[{sentence_embedd...|
+---------+---------+---------+--------------------+--------------------+



In [31]:
overrided_model = bertExtractor.setPretrainedModelPath("/content/sbiobertresolve_snomed_model").setOverrideExistingCodes(True).fit(override_data)
overrided_model.write().overwrite().save("overrided_model")

In [32]:
overrided_resolver = medical.SentenceEntityResolverModel.load("overrided_model") \
      .setInputCols(["ner_chunk", "sbert_embeddings"]) \
      .setOutputCol("overrided_code")


overrided_pipelineModel = nlp.PipelineModel(
    stages = [
        documentAssembler,
        sbert_embedder,
        first_model,
        overrided_resolver])

overrided_lp = nlp.LightPipeline(overrided_pipelineModel)

In [33]:
# original model

display(get_codes (overrided_lp, "Backache", vocab='first_code'))

chunks  begin  end       code  \
0  Backache  0      7    161891005   

                                                                                         all_codes  \
0  [161891005, 279039007, 48926009, 404640003, 367391008, 16269008, 116289008, 81680005, 25064002]   

                                                                                                        resolutions  \
0  [Backache, Low back pain, Pain in spine, Dizziness, Malaise, Neuralgia, Abdominal bloating, Neck pain, Headache]   

                                                              all_distances  
0  [0.0000, 0.1411, 0.1410, 0.1426, 0.1517, 0.1569, 0.1520, 0.1530, 0.1571]

In [34]:
# overrided model

display(get_codes (overrided_lp, "Backache", vocab='overrided_code'))

chunks  begin  end       code  \
0  Backache  0      7    161891005   

                                                                                         all_codes  \
0  [161891005, 279039007, 48926009, 404640003, 367391008, 16269008, 116289008, 81680005, 25064002]   

                                                                                                         resolutions  \
0  [toothache, Low back pain, Pain in spine, Dizziness, Malaise, Neuralgia, Abdominal bloating, Neck pain, Headache]   

                                                              all_distances  
0  [0.1390, 0.1411, 0.1410, 0.1426, 0.1517, 0.1569, 0.1520, 0.1530, 0.1571]

In [35]:
# overrided model

display(get_codes (overrided_lp, "toothache", vocab='overrided_code'))

chunks  begin  end       code  \
0  toothache  0      8    161891005   

                                                                              all_codes  \
0  [161891005, 288939007, 404640003, 22253000, 25064002, 367391008, 53057004, 45534005]   

                                                                                    resolutions  \
0  [toothache, Difficulty swallowing, Dizziness, Pain, Headache, Malaise, Hand pain, Glossitis]   

                                                      all_distances  
0  [0.0000, 0.1266, 0.1317, 0.1340, 0.1360, 0.1415, 0.1379, 0.1457]

As you can see, there is no more `Backache` -> `161891005`. Now all descriptions of `161891005` code are removed and there is just one description `tootache` -> `161891005` for this code.

## Drop List Of Codes

We can drop codes from a pretrained resolver model bu using .`setDropCodesList`. Lets remove `161891005` (toothache) and `404640003` (Dizzeness) from the overrided model.

In [36]:
blackListedModel = bertExtractor.\
    setPretrainedModelPath("overrided_model").\
    setNormalizedCol("_term").\
    setDropCodesList(["161891005", "404640003"]).\
    fit(override_data.limit(0))

In [37]:
blackListedModel.write().overwrite().save("blackListedModel")

In [38]:
blackListed_resolver = medical.SentenceEntityResolverModel.load("blackListedModel") \
      .setInputCols(["ner_chunk", "sbert_embeddings"]) \
      .setOutputCol("blackListed_code")


blackListed_pipelineModel = nlp.PipelineModel(
    stages = [
        documentAssembler,
        sbert_embedder,
        overrided_resolver,
        blackListed_resolver])

blackListed_lp = nlp.LightPipeline(blackListed_pipelineModel)

In [39]:
# overrided model

display(get_codes (blackListed_lp, "toothache", vocab='overrided_code'))

chunks  begin  end       code  \
0  toothache  0      8    161891005   

                                                                              all_codes  \
0  [161891005, 288939007, 404640003, 22253000, 25064002, 367391008, 53057004, 45534005]   

                                                                                    resolutions  \
0  [toothache, Difficulty swallowing, Dizziness, Pain, Headache, Malaise, Hand pain, Glossitis]   

                                                      all_distances  
0  [0.0000, 0.1266, 0.1317, 0.1340, 0.1360, 0.1415, 0.1379, 0.1457]

In [40]:
# blackListed model

display(get_codes (blackListed_lp, "toothache", vocab='blackListed_code'))

chunks  begin  end       code  \
0  toothache  0      8    288939007   

                                                                             all_codes  \
0  [288939007, 22253000, 25064002, 367391008, 53057004, 45534005, 248490000, 18876004]   

                                                                                                resolutions  \
0  [Difficulty swallowing, Pain, Headache, Malaise, Hand pain, Glossitis, Bloating symptom, Pain in finger]   

                                                      all_distances  
0  [0.1266, 0.1340, 0.1360, 0.1415, 0.1379, 0.1457, 0.1395, 0.1412]

In [41]:
# overrided model

display(get_codes (blackListed_lp, "Dizziness", vocab='overrided_code'))

chunks  begin  end       code  \
0  Dizziness  0      8    404640003   

                                                                                                                                                 all_codes  \
0  [404640003, 271782001, 119416008, 271713000, 248490000, 373931001, 310501001, 309838005, 367391008, 301026000, 214264003, 55929007, 7006003, 399153001]   

                                                                                                                                                                                                                              resolutions  \
0  [Dizziness, Drowsy, Epigastric discomfort, General unsteadiness, Bloating symptom, Sensation of heaviness in limbs, Numbness of limbs, Emotional upset, Malaise, Loss of confidence, Lethargy, Feeling irritable, Clumsiness, Vertigo]   

                                                                                                      all_distances  
0  [0.0000, 0.0811, 0.0838, 0.0858, 0.0877, 0.0893, 0.0929, 0.0979, 0.1055, 0.1028, 0.1055, 0.1024, 0.1063, 0.1113]

In [42]:
# blackListed model

display(get_codes (blackListed_lp, "Dizziness", vocab='blackListed_code'))

chunks  begin  end       code  \
0  Dizziness  0      8    271782001   

                                                                                                                                                                         all_codes  \
0  [271782001, 119416008, 271713000, 248490000, 373931001, 310501001, 309838005, 367391008, 301026000, 214264003, 55929007, 7006003, 399153001, 271795006, 101000119102, 53057004]   

                                                                                                                                                                                                                                                                                            resolutions  \
0  [Drowsy, Epigastric discomfort, General unsteadiness, Bloating symptom, Sensation of heaviness in limbs, Numbness of limbs, Emotional upset, Malaise, Loss of confidence, Lethargy, Feeling irritable, Clumsiness, Vertigo, Malaise and fatigue, Numbness and tingling sensation of skin, Hand pain]   

                                                                                                                      all_distances  
0  [0.0811, 0.0838, 0.0858, 0.0877, 0.0893, 0.0929, 0.0979, 0.1055, 0.1028, 0.1055, 0.1024, 0.1063, 0.1113, 0.1097, 0.1104, 0.1125]

As you can see, `161891005`, `404640003` codes are removed from the model.